export const categories: string[] = [
  "Frontend Development",
  "Backend Development",
  "Mobile Development",
  "Cloud & DevOps",
  "AI & Data Science",
  "Design & Tools",
  "Leadership & Soft Skills",
  "Currently Learning",
  "Other",
];

export const iconGroups: { group: string; options: { value: string; label: string }[] }[] = [
  {
    group: "Frontend",
    options: [
      { value: "FaReact", label: "React" },
      { value: "FaVuejs", label: "Vue.js" },
      { value: "FaAngular", label: "Angular" },
      { value: "FaJs", label: "JavaScript" },
      { value: "SiTypescript", label: "TypeScript" },
      { value: "FaHtml5", label: "HTML5" },
      { value: "FaCss3Alt", label: "CSS3" },
      { value: "FaSass", label: "Sass" },
      { value: "SiTailwindcss", label: "Tailwind CSS" },
      { value: "SiBootstrap", label: "Bootstrap" },
      { value: "SiNextdotjs", label: "Next.js" },
      { value: "SiNuxtdotjs", label: "Nuxt.js" },
      { value: "SiSvelte", label: "Svelte" },
      { value: "SiAstro", label: "Astro" },
      { value: "SiRemix", label: "Remix" },
    ],
  },
  {
    group: "Backend",
    options: [
      { value: "FaNodeJs", label: "Node.js" },
      { value: "SiExpress", label: "Express.js" },
      { value: "SiNestjs", label: "NestJS" },
      { value: "FaPython", label: "Python" },
      { value: "SiDjango", label: "Django" },
      { value: "SiFlask", label: "Flask" },
      { value: "SiFastapi", label: "FastAPI" },
      { value: "FaPhp", label: "PHP" },
      { value: "SiLaravel", label: "Laravel" },
      { value: "FaJava", label: "Java" },
      { value: "SiSpring", label: "Spring Boot" },
      { value: "FaRust", label: "Rust" },
      { value: "SiGo", label: "Go/Golang" },
      { value: "SiRuby", label: "Ruby" },
      { value: "SiRubyonrails", label: "Ruby on Rails" },
      { value: "SiCsharp", label: "C#" },
      { value: "SiDotnet", label: ".NET" },
      { value: "SiCplusplus", label: "C++" },
      { value: "SiC", label: "C" },
      { value: "SiKotlin", label: "Kotlin" },
      { value: "SiScala", label: "Scala" },
      { value: "SiElixir", label: "Elixir" },
      { value: "SiGraphql", label: "GraphQL" },
    ],
  },
  {
    group: "Mobile",
    options: [
      { value: "SiFlutter", label: "Flutter" },
      { value: "SiDart", label: "Dart" },
      { value: "SiSwift", label: "Swift" },
      { value: "FaApple", label: "iOS / Apple" },
      { value: "SiIos", label: "iOS" },
      { value: "FaAndroid", label: "Android" },
      { value: "SiAndroid", label: "Android (Simple)" },
      { value: "SiKotlin", label: "Kotlin (Android)" },
      { value: "SiReact", label: "React Native" },
      { value: "SiExpo", label: "Expo" },
      { value: "SiIonic", label: "Ionic" },
      { value: "SiCapacitor", label: "Capacitor" },
      { value: "SiXamarin", label: "Xamarin" },
      { value: "FaMobile", label: "Mobile (Generic)" },
    ],
  },
  {
    group: "Database",
    options: [
      { value: "FaDatabase", label: "Database" },
      { value: "SiMongodb", label: "MongoDB" },
      { value: "SiPostgresql", label: "PostgreSQL" },
      { value: "SiMysql", label: "MySQL" },
      { value: "SiRedis", label: "Redis" },
      { value: "SiSqlite", label: "SQLite" },
      { value: "SiFirebase", label: "Firebase" },
      { value: "SiSupabase", label: "Supabase" },
      { value: "SiPrisma", label: "Prisma" },
      { value: "SiAppwrite", label: "Appwrite" },
    ],
  },
  {
    group: "DevOps & Cloud",
    options: [
      { value: "FaDocker", label: "Docker" },
      { value: "SiKubernetes", label: "Kubernetes" },
      { value: "FaAws", label: "AWS" },
      { value: "FaGoogle", label: "Google Cloud" },
      { value: "FaMicrosoft", label: "Azure" },
      { value: "SiVercel", label: "Vercel" },
      { value: "SiNetlify", label: "Netlify" },
      { value: "SiHeroku", label: "Heroku" },
      { value: "SiDigitalocean", label: "DigitalOcean" },
      { value: "SiCloudflare", label: "Cloudflare" },
      { value: "FaLinux", label: "Linux" },
      { value: "FaUbuntu", label: "Ubuntu" },
      { value: "SiNginx", label: "Nginx" },
      { value: "SiApache", label: "Apache" },
      { value: "SiJenkins", label: "Jenkins" },
      { value: "SiGithubactions", label: "GitHub Actions" },
      { value: "SiCircleci", label: "CircleCI" },
      { value: "SiTerraform", label: "Terraform" },
      { value: "SiAnsible", label: "Ansible" },
    ],
  },
  {
    group: "Tools",
    options: [
      { value: "FaGitAlt", label: "Git" },
      { value: "FaGithub", label: "GitHub" },
      { value: "FaGitlab", label: "GitLab" },
      { value: "FaBitbucket", label: "Bitbucket" },
      { value: "FaNpm", label: "NPM" },
      { value: "FaYarn", label: "Yarn" },
      { value: "SiPnpm", label: "PNPM" },
      { value: "SiVite", label: "Vite" },
      { value: "SiWebpack", label: "Webpack" },
      { value: "SiEsbuild", label: "ESBuild" },
      { value: "SiRollup", label: "Rollup" },
      { value: "SiBabel", label: "Babel" },
      { value: "SiEslint", label: "ESLint" },
      { value: "SiPrettier", label: "Prettier" },
      { value: "SiJest", label: "Jest" },
      { value: "SiCypress", label: "Cypress" },
      { value: "SiPlaywright", label: "Playwright" },
      { value: "SiPostman", label: "Postman" },
      { value: "SiInsomnia", label: "Insomnia" },
    ],
  },
  {
    group: "Design",
    options: [
      { value: "FaFigma", label: "Figma" },
      { value: "FaSketch", label: "Sketch" },
      { value: "SiAdobexd", label: "Adobe XD" },
      { value: "SiAdobephotoshop", label: "Photoshop" },
      { value: "SiAdobeillustrator", label: "Illustrator" },
      { value: "SiCanva", label: "Canva" },
      { value: "SiBlender", label: "Blender" },
      { value: "FaPaintBrush", label: "Design (Generic)" },
    ],
  },
  {
    group: "AI / ML",
    options: [
      { value: "FaRobot", label: "AI / ML" },
      { value: "FaBrain", label: "Machine Learning" },
      { value: "SiTensorflow", label: "TensorFlow" },
      { value: "SiPytorch", label: "PyTorch" },
      { value: "SiOpenai", label: "OpenAI" },
      { value: "SiHuggingface", label: "Hugging Face" },
      { value: "SiJupyter", label: "Jupyter" },
      { value: "SiNumpy", label: "NumPy" },
      { value: "SiPandas", label: "Pandas" },
      { value: "SiScikitlearn", label: "Scikit-learn" },
    ],
  },
  {
    group: "Other",
    options: [
      { value: "FaCode", label: "Code" },
      { value: "FaTerminal", label: "Terminal" },
      { value: "FaCogs", label: "Settings / Config" },
      { value: "FaCloud", label: "Cloud" },
      { value: "FaLock", label: "Security" },
      { value: "FaChartLine", label: "Analytics" },
      { value: "FaNetworkWired", label: "Networking" },
      { value: "FaCube", label: "3D / Graphics" },
      { value: "FaGamepad", label: "Gaming" },
      { value: "SiUnity", label: "Unity" },
      { value: "SiUnrealengine", label: "Unreal Engine" },
      { value: "FaWordpress", label: "WordPress" },
      { value: "FaShopify", label: "Shopify" },
      { value: "SiWoocommerce", label: "WooCommerce" },
      { value: "FaStripe", label: "Stripe" },
      { value: "FaSlack", label: "Slack" },
      { value: "SiDiscord", label: "Discord" },
      { value: "FaTrello", label: "Trello" },
      { value: "FaJira", label: "Jira" },
      { value: "SiNotion", label: "Notion" },
      { value: "SiConfluence", label: "Confluence" },
      { value: "SiMarkdown", label: "Markdown" },
      { value: "SiJson", label: "JSON" },
      { value: "SiYaml", label: "YAML" },
      { value: "SiSolidity", label: "Solidity" },
      { value: "SiWeb3dotjs", label: "Web3.js" },
      { value: "SiEthereum", label: "Ethereum" },
    ],
  },
];

export const iconOptions: { value: string; label: string }[] = iconGroups.flatMap((g) => g.options);

