import type { Event } from "./types";

/** September – December events */
export const eventsSepDec: Event[] = [
  {
    id: "labor-day",
    title: "Happy Labor Day!",
    message:
      "Celebrating the hard work and achievements of workers everywhere!",
    mobileMessage: "Celebrating workers!",
    iconName: "star",
    startDate: { month: 9, day: 1 },
    endDate: { month: 9, day: 1 },
    bgGradient: "from-teal-600 via-oceanic-500 to-oceanic-900",
    showConfetti: false,
  },
  {
    id: "halloween",
    title: "Happy Halloween!",
    message: "Spooky season is here! Hope your Halloween is frighteningly fun!",
    mobileMessage: "Spooky season!",
    iconName: "ghost",
    startDate: { month: 10, day: 31 },
    endDate: { month: 10, day: 31 },
    bgGradient: "from-orange-500 via-teal-600 to-slate-800",
    showConfetti: true,
  },
  {
    id: "veterans-day",
    title: "Veterans Day",
    message:
      "Honoring all who served. Thank you for your sacrifice and service.",
    mobileMessage: "Thank you, veterans",
    iconName: "flag",
    startDate: { month: 11, day: 11 },
    endDate: { month: 11, day: 11 },
    bgGradient: "from-slate-700 via-teal-600 to-slate-700",
    showConfetti: false,
  },
  {
    id: "thanksgiving",
    title: "Happy Thanksgiving!",
    message:
      "Grateful for visitors like you! Wishing you a wonderful Thanksgiving.",
    mobileMessage: "Grateful for you!",
    iconName: "leaf",
    startDate: { month: 11, day: 27 },
    endDate: { month: 11, day: 28 },
    bgGradient: "from-amber-500 via-teal-500 to-emerald-500",
    showConfetti: true,
  },
  {
    id: "christmas",
    title: "Merry Christmas!",
    message: "Wishing you a magical holiday season filled with joy and warmth!",
    mobileMessage: "Merry Christmas!",
    iconName: "tree",
    startDate: { month: 12, day: 24 },
    endDate: { month: 12, day: 26 },
    bgGradient: "from-emerald-600 via-teal-500 to-oceanic-500",
    showConfetti: true,
  },
  {
    id: "hanukkah",
    title: "Happy Hanukkah!",
    message: "Wishing you a bright and joyful Festival of Lights!",
    mobileMessage: "Happy Hanukkah!",
    iconName: "star",
    startDate: { month: 12, day: 14 },
    endDate: { month: 12, day: 22 },
    bgGradient: "from-blue-500 via-oceanic-400 to-teal-400",
    showConfetti: true,
  },
  {
    id: "kwanzaa",
    title: "Happy Kwanzaa!",
    message: "Celebrating African heritage, culture, and community!",
    mobileMessage: "Happy Kwanzaa!",
    iconName: "drum",
    startDate: { month: 12, day: 26 },
    endDate: { month: 12, day: 31 },
    bgGradient: "from-emerald-700 via-teal-600 to-amber-500",
    showConfetti: true,
  },
  {
    id: "new-years-eve",
    title: "Happy New Year's Eve!",
    message: "Cheers to new beginnings! See you in the new year!",
    mobileMessage: "Cheers to 2026!",
    iconName: "star",
    startDate: { month: 12, day: 31 },
    endDate: { month: 12, day: 31 },
    bgGradient: "from-teal-600 via-oceanic-500 to-emerald-500",
    showConfetti: true,
  },
];
