import type { Event } from "./types";

/** April – July events */
export const eventsAprJul: Event[] = [
  {
    id: "easter",
    title: "Happy Easter!",
    message: "Wishing you a joyful Easter filled with hope and renewal!",
    mobileMessage: "Happy Easter!",
    iconName: "egg",
    startDate: { month: 4, day: 20 },
    endDate: { month: 4, day: 21 },
    bgGradient: "from-oceanic-400 to-oceanic-600",
    showConfetti: true,
  },
  {
    id: "birthday",
    title: "It's My Birthday!",
    message:
      "April 28th is my special day! Thanks for visiting my portfolio. Feel free to leave a birthday wish!",
    mobileMessage: "It's my birthday!",
    iconName: "birthday",
    startDate: { month: 4, day: 28 },
    endDate: { month: 4, day: 28 },
    bgGradient: "from-oceanic-500 via-oceanic-600 to-oceanic-800",
    showConfetti: true,
  },
  {
    id: "workers-day-ghana",
    title: "Ghana Workers' Day!",
    message:
      "Celebrating the dignity of work and the contributions of workers in Ghana and beyond!",
    mobileMessage: "Happy Workers' Day!",
    iconName: "star",
    startDate: { month: 5, day: 1 },
    endDate: { month: 5, day: 1 },
    bgGradient: "from-oceanic-500 to-oceanic-800",
    showConfetti: false,
  },
  {
    id: "mothers-day",
    title: "Happy Mother's Day!",
    message: "Celebrating all the amazing moms out there! You are appreciated.",
    mobileMessage: "Love to all moms!",
    iconName: "heart",
    startDate: { month: 5, day: 11 },
    endDate: { month: 5, day: 11 },
    bgGradient: "from-oceanic-400 to-oceanic-700",
    showConfetti: true,
  },
  {
    id: "memorial-day",
    title: "Memorial Day",
    message: "Honoring those who made the ultimate sacrifice for our freedom.",
    mobileMessage: "Honoring our heroes",
    iconName: "flag",
    startDate: { month: 5, day: 26 },
    endDate: { month: 5, day: 26 },
    bgGradient: "from-oceanic-700 to-oceanic-900",
    showConfetti: false,
  },
  {
    id: "fathers-day",
    title: "Happy Father's Day!",
    message: "Celebrating all the wonderful dads! Thank you for everything.",
    mobileMessage: "Love to all dads!",
    iconName: "gift",
    startDate: { month: 6, day: 15 },
    endDate: { month: 6, day: 15 },
    bgGradient: "from-oceanic-600 to-oceanic-900",
    showConfetti: true,
  },
  {
    id: "pride-month",
    title: "Happy Pride Month!",
    message: "Celebrating love, diversity, and equality for all!",
    mobileMessage: "Love is love!",
    iconName: "heart",
    startDate: { month: 6, day: 1 },
    endDate: { month: 6, day: 30 },
    bgGradient: "from-oceanic-400 via-oceanic-500 to-oceanic-700",
    showConfetti: true,
  },
  {
    id: "juneteenth",
    title: "Juneteenth",
    message: "Celebrating freedom and the end of slavery in America.",
    mobileMessage: "Celebrating freedom",
    iconName: "star",
    startDate: { month: 6, day: 19 },
    endDate: { month: 6, day: 19 },
    bgGradient: "from-oceanic-600 to-oceanic-900",
    showConfetti: false,
  },
  {
    id: "ghana-republic-day",
    title: "Ghana Republic Day!",
    message: "Celebrating Ghana's first Republic in 1960, a proud milestone in African democracy!",
    mobileMessage: "Ghana Republic Day!",
    iconName: "star",
    startDate: { month: 7, day: 1 },
    endDate: { month: 7, day: 1 },
    bgGradient: "from-oceanic-500 via-oceanic-600 to-oceanic-800",
    showConfetti: true,
  },
  {
    id: "independence-day",
    title: "Happy 4th of July!",
    message: "Celebrating Independence Day! Land of the free, home of the brave.",
    mobileMessage: "Happy 4th!",
    iconName: "flag",
    startDate: { month: 7, day: 4 },
    endDate: { month: 7, day: 4 },
    bgGradient: "from-oceanic-500 to-oceanic-800",
    showConfetti: true,
  },
];
