import {
  FaChartBar,
  FaEnvelope,
  FaCalendarAlt,
  FaComments,
  FaUser,
  FaCode,
  FaProjectDiagram,
  FaFileAlt,
  FaBlog,
  FaQuoteRight,
  FaGraduationCap,
  FaRoad,
  FaImage,
  FaCog,
  FaBriefcase,
  FaFileInvoiceDollar,
  FaChartLine,
  FaDatabase,
  FaCreditCard,
} from "react-icons/fa";
import type { IconType } from "react-icons";
import type { TabType } from "./types";

export const allTabs: Array<{ id: TabType; label: string; icon: IconType }> = [
  { id: "overview", label: "Overview", icon: FaChartBar },
  { id: "messages", label: "Messages", icon: FaEnvelope },
  { id: "bookings", label: "Bookings", icon: FaCalendarAlt },
  { id: "client-work", label: "Client Work", icon: FaBriefcase },
  { id: "invoices", label: "Invoices", icon: FaFileInvoiceDollar },
  { id: "payments", label: "Payments", icon: FaCreditCard },
  { id: "analytics", label: "Analytics", icon: FaChartLine },
  { id: "comments", label: "Comments", icon: FaComments },
  { id: "about", label: "About Me", icon: FaUser },
  { id: "skills", label: "Skills", icon: FaCode },
  { id: "projects", label: "Projects", icon: FaProjectDiagram },
  { id: "certifications", label: "Certifications", icon: FaFileAlt },
  { id: "blog", label: "Blog Posts", icon: FaBlog },
  { id: "testimonials", label: "Testimonials", icon: FaQuoteRight },
  { id: "education", label: "Education", icon: FaGraduationCap },
  { id: "journey", label: "Journey", icon: FaRoad },
  { id: "gallery", label: "Gallery", icon: FaImage },
  { id: "storage", label: "Storage", icon: FaDatabase },
  { id: "settings", label: "Settings", icon: FaCog },
];
