import type { TabContentProps } from "./TabContentProps";
import type { DashboardState } from "./useDashboardState";
import type { BlogPost, Testimonial } from "@/types";

export function buildTabContentProps(
  s: DashboardState,
  isReadOnly: boolean,
): TabContentProps {
  return {
    activeTab: s.activeTab,
    theme: s.theme,
    loading: s.loading,
    isReadOnly,
    searchQuery: s.searchQuery,
    filteredMessages: s.filtered.filteredMessages,
    filteredSkills: s.filtered.filteredSkills,
    filteredProjects: s.filtered.filteredProjects,
    filteredCertifications: s.filtered.filteredCertifications,
    filteredGallery: s.filtered.filteredGallery,
    filteredEducation: s.filtered.filteredEducation,
    filteredJourney: s.filtered.filteredJourney,
    filteredBlogPosts: s.filtered.filteredBlogPosts,
    newMessages: s.newMessages,
    totalMessages: s.messages.length,
    totalProjects: s.projects.length,
    totalCertifications: s.certifications.length,
    totalGallery: s.gallery.length,
    siteViews: s.adminData.siteViews,
    onSearchChange: s.setSearchQuery,
    onTabChange: s.setActiveTab,
    openNewProject: s.modals.openNewProject,
    openEditProject: s.modals.openEditProject,
    openNewSkill: s.modals.openNewSkill,
    openEditSkill: s.modals.openEditSkill,
    openNewCertification: s.modals.openNewCertification,
    openEditCertification: s.modals.openEditCertification,
    openNewEducation: s.modals.openNewEducation,
    openEditEducation: s.modals.openEditEducation,
    openNewJourney: s.modals.openNewJourney,
    openEditJourney: s.modals.openEditJourney,
    openNewGalleryImage: s.modals.openNewGalleryImage,
    openEditGalleryImage: s.modals.openEditGalleryImage,
    handleMessageStatusChange: s.deleteConfirmHook.handleMessageStatusChange,
    requestDeleteMessage: s.deleteConfirmHook.requestDeleteMessage,
    requestDeleteSkill: s.deleteConfirmHook.requestDeleteSkill,
    handleDeleteProject: s.adminData.handleDeleteProject,
    handleDeleteCertification: s.adminData.handleDeleteCertification,
    handleDeleteGalleryImage: s.adminData.handleDeleteGalleryImage,
    handleUpdateGalleryOrder: s.adminData.handleUpdateGalleryOrder,
    handleToggleGalleryVisibility: s.adminData.handleToggleGalleryVisibility,
    handleDeleteEducation: s.adminData.handleDeleteEducation,
    handleDeleteJourney: s.adminData.handleDeleteJourney,
    about: s.adminData.about,
    handleSaveAbout: s.adminData.handleSaveAbout,
    handleAddBlogPost: (post) =>
      s.adminData.handleAddBlogPost(post as Omit<BlogPost, "$id">),
    handleUpdateBlogPost: s.adminData.handleUpdateBlogPost,
    handleDeleteBlogPost: s.adminData.handleDeleteBlogPost,
    testimonials: s.adminData.testimonials,
    handleDeleteTestimonial: s.adminData.handleDeleteTestimonial,
    handleUpdateTestimonial: s.adminData.handleUpdateTestimonial,
    handleAddTestimonial: s.adminData.handleAddTestimonial,
    setEditingTestimonial: (t: Testimonial | null) => { if (t) s.modals.openEditTestimonial(t); },
    setShowTestimonialModal: (show: boolean) => {
      if (show) s.modals.openNewTestimonial();
    },
    showSuccess: s.showSuccess,
    showError: s.showError,
  };
}
